In [2]:
import pandas as pd
import numpy as np
# Create a simple dataset
data = {
    "Name": ['Ajit Doval', 'Hamza Ali', 'Jassi Singh', 'Jameel Jamali'], 
    "Marks": [90, 95, 92, 99] 
    }
df = pd.DataFrame(data)
# Replace 'NA' with np.nan
df.replace('NA', np.nan, inplace = True)
# Save the dataset
df.to_csv("data.csv", index  = False)
# Load it back
df = pd.read_csv("data.csv")
pd.set_option('display.max_rows', None)
# access specific columns
df.Name
df[['Name', 'Marks']]
# see all the column names
df.columns
# access rows by integer location
df.iloc[0]
df.iloc[[0, 1]]
# access rows and columns using integer location- (row, column)
df.iloc[[0, 2], [0,1]]
# using loc
df.loc[[0, 3], 'Name']
df.loc[[0, 3], ['Name', 'Marks']]
# Filter marks
df[df["Marks"] > 90]
# reverse selection
df.iloc[::-1]
# select last 3 rows
df.iloc[-3:]
# multi-condition filter
df["Honor roll"] = df["Marks"] >= 95
df.loc[(df["Marks"] > 90) & (df["Honor roll"] == True)]
# setting the index
df.set_index("Name", inplace = True)
df.index
df.loc["Ajit Doval", 'Marks']
df.reset_index(inplace = True)
# Anyone who has 'J' in their name
df[df["Name"].str.contains('J')]
# add new rows
new_row = pd.DataFrame([{'Name': 'Pinda Yaara', 'Marks': 57}])
df = pd.concat([df, new_row], ignore_index=True)
# Create new columns
df["Grade"] = df["Marks"] / 25
df.loc[df["Marks"] >= 95, "Status"] = "Excellent"
df.loc[df["Marks"] < 95, "Status"] = "Good"
df.loc[df["Honor roll"] == True, "PerformanceScore"] = df["Marks"] * 1
df.loc[df["Honor roll"] == False, "PerformanceScore"] = df["Marks"] * 0.9
# Rename the column
df.rename(columns = {"Grade": "GPA"}, inplace = True)
df
# Runnung "apply" on a series
df["Name"].apply(len)
def update_name(name):
    return name.upper()
df["Name"].apply(update_name)
df["Name"] = df["Name"].apply(lambda x : x.upper())
# running "apply" on a dataframe
df.apply(pd.Series.min)
# running "map"
df["Name"].map(len)
df["Name"].map(str.lower)
df["Name"].map({"Ajit" : "Pinda", "Hamza" : "Alam"})
# using "replace": wont put Null for values not assigned
df["Name"].replace({"Ajit" : "Pinda", "Hamza" : "Alam"})
# Removing the Status column
df.drop(columns = "Status", inplace = True)
# add new columns 
df[["first_name", "last_name"]] = df["Name"].str.split(" ", expand = True)
# Removing a row
df.drop(index = 3)
# Sorting by last name
df = df.sort_values(by = "last_name", ascending = False)
# Handling missing values
df.dropna(axis = 'index', how = 'all', subset = ["Name"])
# Check for missing values
df.isna()
# Fill missing values with a specific value
df["Marks"].fillna(df["Marks"].mean(), inplace = True)
# Convert Marks to float
df["Marks"] = df["Marks"].astype(float)
# Check data types
df.dtypes
df

C:\Users\admin\AppData\Local\Temp\ipykernel_6396\1356902800.py:84: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(df["Marks"].mean(), inplace = True)

,Name,Marks,Honor roll,GPA,PerformanceScore,first_name,last_name
4,PINDA YAARA,57.0,NaN,2.28,NaN,PINDA,YAARA
2,JASSI SINGH,92.0,False,3.68,82.8,JASSI,SINGH
3,JAMEEL JAMALI,99.0,True,3.96,99.0,JAMEEL,JAMALI
0,AJIT DOVAL,90.0,False,3.60,81.0,AJIT,DOVAL
1,HAMZA ALI,95.0,True,3.80,95.0,HAMZA,ALI

In [1]:
import pandas as pd
# Define custom NA values
na_vals = ["Missing", "NA"]
# Load the dataset with specified NA values
df = pd.read_csv('survey_results_public.csv', index_col = 'ResponseId', keep_default_na=False, na_values=na_vals)
schema_df = pd.read_csv('survey_results_schema.csv', index_col = 'qname')
# number of rows and columns
df.shape   
# info about the dataset
df.info()
# to see a set amount of columns
pd.set_option('display.max_columns', 25)
# to see a set amount of columns
pd.set_option('display.max_rows', 25)
df
# see the first n rows
display(df.head())
# see the last n rows
df.tail()
# to see how many rows have a particular value for the selected column
df.Age.value_counts()
# all columns for the first row
df.loc[0]
# find a specific column for a specific row
df.loc[0, 'Age']
df.loc[[0,1,2,3], 'Age']
# to sort the index
schema_df.sort_index(inplace = True)
df.loc[0 : 5]
# know the meaning of column name from schema CSV
schema_df.loc["ConvertedCompYearly", "question"]
# Filtering based on salary
high_salary = df["ConvertedCompYearly"] > 70000
df.loc[high_salary, ["Country",  "LanguageChoice" ,"ConvertedCompYearly", "WorkExp", "YearsCode"]]
# Filtering based on Country
countries = ["India", "Pakistan", "Canada"]
filt = df["Country"].isin(countries)
df.loc[filt, ["Country","ConvertedCompYearly", "WorkExp", "YearsCode"]]
# To look for a particular country
df[df["Country"] == "Germany"]
df.rename(columns = {"ConvertedCompYearly" : "SalaryUSD"}, inplace = True)
df['AIAgentChange'] = df['AIAgentChange'].map({"Yes":True,"No":False})
df.sort_values(by = ["Country", "SalaryUSD"], ascending = [True, False], inplace = True)
df[["Country", "SalaryUSD"]].head(50)
# Top 10 Largest salaries
df["SalaryUSD"].nlargest(10)
df.nlargest(10, "SalaryUSD")
# Median of all salaries
df["ConvertedCompYearly"].median()
# Median of all numeric values
df.median(numeric_only = True)
# to get different functions
df.describe()
df["Age"].describe()
# How many people answered what
df["MainBranch"].value_counts()
# what percentage of people answered what
df["SOAccount"].value_counts(normalize = True)
# Grouping by Country
country_grp = df.groupby("Country")
country_grp.get_group("Netherlands")
# finding different ages in a particular country
df.loc[df["Country"] == "India"]["Age"].value_counts()
# Number of people with SOAccount in each country
country_grp["SOAccount"].value_counts().head(50)
# Number of people with SOAccount in India
country_grp["SOAccount"].value_counts().loc["India"]
country_grp["ConvertedCompYearly"].median().loc[["India", "United States of America", "Pakistan", "France", "Germany"]]
# To run multiple aggregate functions
country_grp["ConvertedCompYearly"].agg(['median', 'mean']).loc[["India", "United States of America", "Pakistan", "France", "Germany"]]
# Number of people who have worked with Python in each country using filtering
df.loc[df["Country"] == "India"]["LanguageHaveWorkedWith"].str.contains("Python").sum()
# Number of people who have worked with Python in each country using grouping
country_grp["LanguageHaveWorkedWith"].apply(lambda x: x.str.contains("Python").sum())
# Percentage of people who have worked with Python in each country using grouping
country_grp["LanguageHaveWorkedWith"].apply(lambda x: x.str.contains("Python").value_counts(normalize = True) * 100).sort_values(ascending = False)
# Percentage of people who have worked with Python in a specific country using grouping
country_grp["LanguageHaveWorkedWith"].apply(lambda x: x.str.contains("Python").value_counts(normalize = True) * 100).loc["Canada"]
# Unique values in YearsCode column
df["YearsCode"].unique()
# Mean of all numeric values
df["YearsCode"].mean()
# Median of all numeric values
df["YearsCode"].median()

C:\Users\admin\AppData\Local\Temp\ipykernel_10796\499041962.py:5: DtypeWarning: Columns (0: AIThreat, 1: DatabaseWantEntry, 2: DevEnvWantEntry, 3: SOTagsWant Entry, 4: OpSysPersonal use, 5: CommPlatformHaveWorkedWith, 6: CommPlatformWantEntr, 7: AIModelsChoice, 8: SOComm, 9: AIAgentOrchWrite, 10: AIAgentExternal) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('survey_results_public.csv', index_col = 'ResponseId', keep_default_na=False, na_values=na_vals)

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 1 to 49191
Columns: 171 entries, MainBranch to JobSat
dtypes: float64(52), str(119)
memory usage: 64.2 MB

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,...,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",...,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",...,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end",...,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

KeyError: 0