In [ ]:
import pandas as pd
# Create a simple dataset
data = {
    "Name": ['Ajit', 'Hamza', 'Jassi', 'Jameel'], 
    "Marks": [90, 95, 92, 99], 
    "Honor roll": ['No', 'Yes', 'No', 'Yes']
    }
df = pd.DataFrame(data)
# Save the dataset
df.to_csv("data.csv", index  = False)
# Load it back
df = pd.read_csv("data.csv")
# access specific columns
df.Name
df[['Name', 'Marks']]
# see all the column names
df.columns
# access rows by integer location
df.iloc[0]
df.iloc[[0, 1]]
# access rows and columns using integer location- (row, column)
df.iloc[[0, 2], [0,1]]
# using loc
df.loc[[0, 3], 'Name']
df.loc[[0, 3], ['Name', 'Marks']]
# Filter marks
df[df["Marks"] > 90]

     Name  Marks Honor roll
1   Hamza     95        Yes
2   Jassi     92         No
3  Jameel     99        Yes

In [ ]:
import pandas as pd
df = pd.read_csv('survey_results_public.csv')
schema_df = pd.read_csv('survey_results_schema.csv')
# number of rows and columns
df.shape   
# info about the dataset
df.info()
# to see a set amount of columns
pd.set_option('display.max_columns', 3)
# to see a set amount of columns
pd.set_option('display.max_rows', 3)
df
# see the first n rows
display(df.head())
# see the last n rows
df.tail()
# to see how many rows have a particular value for the selected column
df.Age.value_counts()
# all columns for the first row
df.loc[0]
# find a specific column for a specific row
df.loc[0, 'Age']
df.loc[[0,1,2,3], 'Age']
df.loc[0 : 5, 'Age' : 'Employment']

C:\Users\admin\AppData\Local\Temp\ipykernel_12076\2643154232.py:2: DtypeWarning: Columns (0: JobSatPoints_15_TEXT, 1: DatabaseHaveEntry, 2: DevEnvHaveEntry, 3: SOTagsHaveEntry, 4: SOTagsWant Entry, 5: OfficeStackWantEntry, 6: CommPlatformHaveEntr, 7: CommPlatformWantEntr, 8: SO_Actions_15_TEXT, 9: AIAgentOrchestration, 10: AIAgentObsWrite) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('survey_results_public.csv')

,Age,EdLevel,Employment
0,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed
1,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed
2,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em..."
3,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed
4,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em..."
5,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em..."